// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/matrix.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthResult dco_decode_auth_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  StoredSession dco_decode_box_autoadd_stored_session(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  ChatRoom dco_decode_chat_room(dynamic raw);

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw);

  @protected
  Contact dco_decode_contact(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  List<ChatRoom> dco_decode_list_chat_room(dynamic raw);

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Space> dco_decode_list_space(dynamic raw);

  @protected
  MessageType dco_decode_message_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  StoredSession? dco_decode_opt_box_autoadd_stored_session(dynamic raw);

  @protected
  Space dco_decode_space(dynamic raw);

  @protected
  StoredSession dco_decode_stored_session(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthResult sse_decode_auth_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  StoredSession sse_decode_box_autoadd_stored_session(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  ChatRoom sse_decode_chat_room(SseDeserializer deserializer);

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer);

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  List<ChatRoom> sse_decode_list_chat_room(SseDeserializer deserializer);

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Space> sse_decode_list_space(SseDeserializer deserializer);

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  StoredSession? sse_decode_opt_box_autoadd_stored_session(
    SseDeserializer deserializer,
  );

  @protected
  Space sse_decode_space(SseDeserializer deserializer);

  @protected
  StoredSession sse_decode_stored_session(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_result(AuthResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stored_session(
    StoredSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_chat_room(ChatRoom self, SseSerializer serializer);

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_room(List<ChatRoom> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_space(List<Space> self, SseSerializer serializer);

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stored_session(
    StoredSession? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_space(Space self, SseSerializer serializer);

  @protected
  void sse_encode_stored_session(StoredSession self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
