// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/matrix.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AppLogEntry> dco_decode_StreamSink_app_log_entry_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  RustStreamSink<TypingNotification>
  dco_decode_StreamSink_typing_notification_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  AppLogEntry dco_decode_app_log_entry(dynamic raw);

  @protected
  AuthResult dco_decode_auth_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeviceVerificationStatus dco_decode_box_autoadd_device_verification_status(
    dynamic raw,
  );

  @protected
  StoredSession dco_decode_box_autoadd_stored_session(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  ChatRoom dco_decode_chat_room(dynamic raw);

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw);

  @protected
  Contact dco_decode_contact(dynamic raw);

  @protected
  DeviceVerificationStatus dco_decode_device_verification_status(dynamic raw);

  @protected
  EncryptionRecoveryInfo dco_decode_encryption_recovery_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw);

  @protected
  List<AppLogEntry> dco_decode_list_app_log_entry(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  List<ChatRoom> dco_decode_list_chat_room(dynamic raw);

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw);

  @protected
  List<MessageReader> dco_decode_list_message_reader(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<Space> dco_decode_list_space(dynamic raw);

  @protected
  List<VerificationDevice> dco_decode_list_verification_device(dynamic raw);

  @protected
  List<VerificationEmoji> dco_decode_list_verification_emoji(dynamic raw);

  @protected
  MessageReader dco_decode_message_reader(dynamic raw);

  @protected
  MessageType dco_decode_message_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DeviceVerificationStatus?
  dco_decode_opt_box_autoadd_device_verification_status(dynamic raw);

  @protected
  StoredSession? dco_decode_opt_box_autoadd_stored_session(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  Space dco_decode_space(dynamic raw);

  @protected
  SpaceDetails dco_decode_space_details(dynamic raw);

  @protected
  StoredSession dco_decode_stored_session(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  TypingNotification dco_decode_typing_notification(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  VerificationDevice dco_decode_verification_device(dynamic raw);

  @protected
  VerificationEmoji dco_decode_verification_emoji(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AppLogEntry> sse_decode_StreamSink_app_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TypingNotification>
  sse_decode_StreamSink_typing_notification_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  AppLogEntry sse_decode_app_log_entry(SseDeserializer deserializer);

  @protected
  AuthResult sse_decode_auth_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeviceVerificationStatus sse_decode_box_autoadd_device_verification_status(
    SseDeserializer deserializer,
  );

  @protected
  StoredSession sse_decode_box_autoadd_stored_session(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  ChatRoom sse_decode_chat_room(SseDeserializer deserializer);

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer);

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer);

  @protected
  DeviceVerificationStatus sse_decode_device_verification_status(
    SseDeserializer deserializer,
  );

  @protected
  EncryptionRecoveryInfo sse_decode_encryption_recovery_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer);

  @protected
  List<AppLogEntry> sse_decode_list_app_log_entry(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  List<ChatRoom> sse_decode_list_chat_room(SseDeserializer deserializer);

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer);

  @protected
  List<MessageReader> sse_decode_list_message_reader(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<Space> sse_decode_list_space(SseDeserializer deserializer);

  @protected
  List<VerificationDevice> sse_decode_list_verification_device(
    SseDeserializer deserializer,
  );

  @protected
  List<VerificationEmoji> sse_decode_list_verification_emoji(
    SseDeserializer deserializer,
  );

  @protected
  MessageReader sse_decode_message_reader(SseDeserializer deserializer);

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DeviceVerificationStatus?
  sse_decode_opt_box_autoadd_device_verification_status(
    SseDeserializer deserializer,
  );

  @protected
  StoredSession? sse_decode_opt_box_autoadd_stored_session(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  Space sse_decode_space(SseDeserializer deserializer);

  @protected
  SpaceDetails sse_decode_space_details(SseDeserializer deserializer);

  @protected
  StoredSession sse_decode_stored_session(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  TypingNotification sse_decode_typing_notification(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  VerificationDevice sse_decode_verification_device(
    SseDeserializer deserializer,
  );

  @protected
  VerificationEmoji sse_decode_verification_emoji(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_log_entry_Sse(
    RustStreamSink<AppLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_typing_notification_Sse(
    RustStreamSink<TypingNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_log_entry(AppLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_auth_result(AuthResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_verification_status(
    DeviceVerificationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_session(
    StoredSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_chat_room(ChatRoom self, SseSerializer serializer);

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer);

  @protected
  void sse_encode_device_verification_status(
    DeviceVerificationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encryption_recovery_info(
    EncryptionRecoveryInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_app_log_entry(
    List<AppLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_room(List<ChatRoom> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_reader(
    List<MessageReader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_space(List<Space> self, SseSerializer serializer);

  @protected
  void sse_encode_list_verification_device(
    List<VerificationDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_verification_emoji(
    List<VerificationEmoji> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_reader(MessageReader self, SseSerializer serializer);

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_device_verification_status(
    DeviceVerificationStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_session(
    StoredSession? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_space(Space self, SseSerializer serializer);

  @protected
  void sse_encode_space_details(SpaceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_stored_session(StoredSession self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_typing_notification(
    TypingNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_verification_device(
    VerificationDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_verification_emoji(
    VerificationEmoji self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
