// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/matrix.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1494476021;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_matter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMatrixCreateClient({
    required String homeserverUrl,
    required String dataDir,
  });

  Future<String> crateApiMatrixCreateDm({required String userId});

  Future<String> crateApiMatrixCreateGroupRoom({
    required String name,
    String? topic,
  });

  Future<Uint8List?> crateApiMatrixDownloadMediaBytes({required String mxcUrl});

  Future<String?> crateApiMatrixGetAccessToken();

  Future<String?> crateApiMatrixGetActiveUserId();

  Future<List<ChatRoom>> crateApiMatrixGetChatRooms();

  ConnectionStatus crateApiMatrixGetConnectionStatus();

  Future<List<Contact>> crateApiMatrixGetContacts();

  Future<String?> crateApiMatrixGetCurrentUserId();

  Future<List<ChatMessage>> crateApiMatrixGetMessages({required String roomId});

  Future<List<ChatMessage>> crateApiMatrixGetMessagesBefore({
    required String roomId,
    required String fromEventId,
    required int limit,
  });

  List<AppLogEntry> crateApiMatrixGetRecentLogs();

  Future<String?> crateApiMatrixGetRoomAvatarUrl({required String roomId});

  Future<List<Contact>> crateApiMatrixGetRoomMembers({required String roomId});

  Future<StoredSession?> crateApiMatrixGetSession();

  Future<List<Space>> crateApiMatrixGetSpaces();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiMatrixInitClient();

  Future<bool> crateApiMatrixIsConnected();

  Future<bool> crateApiMatrixIsLoggedIn();

  Future<List<AccountInfo>> crateApiMatrixListAccounts();

  Future<AuthResult> crateApiMatrixLoginWithPassword({
    required String username,
    required String password,
  });

  Future<AuthResult> crateApiMatrixLoginWithToken({
    required String accessToken,
    required String userId,
    required String deviceId,
  });

  Future<void> crateApiMatrixLogout();

  Future<String?> crateApiMatrixMxcToHttp({required String mxcUrl});

  Future<String?> crateApiMatrixMxcToHttpFull({required String mxcUrl});

  Future<void> crateApiMatrixRedactMessage({
    required String roomId,
    required String eventId,
    String? reason,
  });

  Future<AuthResult> crateApiMatrixRegisterCompleteUiaa({
    required String username,
    required String password,
    required String registrationToken,
    required String session,
  });

  Future<AuthResult> crateApiMatrixRegisterGetUiaaSession({
    required String username,
    required String password,
  });

  Future<void> crateApiMatrixRemoveAccount({required String userId});

  Future<void> crateApiMatrixRestoreSession({
    required StoredSession session,
    required String dataDir,
  });

  Future<List<ChatRoom>> crateApiMatrixSearchRooms({required String query});

  Future<void> crateApiMatrixSendImageMessage({
    required String roomId,
    required List<int> imageData,
    required String filename,
  });

  Future<void> crateApiMatrixSendMessage({
    required String roomId,
    required String message,
  });

  Future<void> crateApiMatrixSendReply({
    required String roomId,
    required String message,
    required String replyToEventId,
  });

  Future<void> crateApiMatrixSendTypingNotice({
    required String roomId,
    required bool typing,
  });

  Future<void> crateApiMatrixStartSync();

  Future<bool> crateApiMatrixSwitchAccount({required String userId});

  Future<void> crateApiMatrixSyncOnce();

  Stream<AppLogEntry> crateApiMatrixWatchAppLogs();

  Stream<SyncEvent> crateApiMatrixWatchSyncEvents();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMatrixCreateClient({
    required String homeserverUrl,
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserverUrl, serializer);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixCreateClientConstMeta,
        argValues: [homeserverUrl, dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateClientConstMeta => const TaskConstMeta(
    debugName: "create_client",
    argNames: ["homeserverUrl", "dataDir"],
  );

  @override
  Future<String> crateApiMatrixCreateDm({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixCreateDmConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateDmConstMeta =>
      const TaskConstMeta(debugName: "create_dm", argNames: ["userId"]);

  @override
  Future<String> crateApiMatrixCreateGroupRoom({
    required String name,
    String? topic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(topic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixCreateGroupRoomConstMeta,
        argValues: [name, topic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateGroupRoomConstMeta =>
      const TaskConstMeta(
        debugName: "create_group_room",
        argNames: ["name", "topic"],
      );

  @override
  Future<Uint8List?> crateApiMatrixDownloadMediaBytes({
    required String mxcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mxcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixDownloadMediaBytesConstMeta,
        argValues: [mxcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixDownloadMediaBytesConstMeta =>
      const TaskConstMeta(
        debugName: "download_media_bytes",
        argNames: ["mxcUrl"],
      );

  @override
  Future<String?> crateApiMatrixGetAccessToken() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetAccessTokenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetAccessTokenConstMeta =>
      const TaskConstMeta(debugName: "get_access_token", argNames: []);

  @override
  Future<String?> crateApiMatrixGetActiveUserId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetActiveUserIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetActiveUserIdConstMeta =>
      const TaskConstMeta(debugName: "get_active_user_id", argNames: []);

  @override
  Future<List<ChatRoom>> crateApiMatrixGetChatRooms() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_room,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetChatRoomsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetChatRoomsConstMeta =>
      const TaskConstMeta(debugName: "get_chat_rooms", argNames: []);

  @override
  ConnectionStatus crateApiMatrixGetConnectionStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetConnectionStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetConnectionStatusConstMeta =>
      const TaskConstMeta(debugName: "get_connection_status", argNames: []);

  @override
  Future<List<Contact>> crateApiMatrixGetContacts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_contact,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetContactsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetContactsConstMeta =>
      const TaskConstMeta(debugName: "get_contacts", argNames: []);

  @override
  Future<String?> crateApiMatrixGetCurrentUserId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetCurrentUserIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetCurrentUserIdConstMeta =>
      const TaskConstMeta(debugName: "get_current_user_id", argNames: []);

  @override
  Future<List<ChatMessage>> crateApiMatrixGetMessages({
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetMessagesConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetMessagesConstMeta =>
      const TaskConstMeta(debugName: "get_messages", argNames: ["roomId"]);

  @override
  Future<List<ChatMessage>> crateApiMatrixGetMessagesBefore({
    required String roomId,
    required String fromEventId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(fromEventId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetMessagesBeforeConstMeta,
        argValues: [roomId, fromEventId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetMessagesBeforeConstMeta =>
      const TaskConstMeta(
        debugName: "get_messages_before",
        argNames: ["roomId", "fromEventId", "limit"],
      );

  @override
  List<AppLogEntry> crateApiMatrixGetRecentLogs() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_app_log_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetRecentLogsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetRecentLogsConstMeta =>
      const TaskConstMeta(debugName: "get_recent_logs", argNames: []);

  @override
  Future<String?> crateApiMatrixGetRoomAvatarUrl({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetRoomAvatarUrlConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetRoomAvatarUrlConstMeta =>
      const TaskConstMeta(
        debugName: "get_room_avatar_url",
        argNames: ["roomId"],
      );

  @override
  Future<List<Contact>> crateApiMatrixGetRoomMembers({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_contact,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetRoomMembersConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetRoomMembersConstMeta =>
      const TaskConstMeta(debugName: "get_room_members", argNames: ["roomId"]);

  @override
  Future<StoredSession?> crateApiMatrixGetSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_stored_session,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixGetSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetSessionConstMeta =>
      const TaskConstMeta(debugName: "get_session", argNames: []);

  @override
  Future<List<Space>> crateApiMatrixGetSpaces() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_space,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetSpacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetSpacesConstMeta =>
      const TaskConstMeta(debugName: "get_spaces", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiMatrixInitClient() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixInitClientConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixInitClientConstMeta =>
      const TaskConstMeta(debugName: "init_client", argNames: []);

  @override
  Future<bool> crateApiMatrixIsConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixIsConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixIsConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_connected", argNames: []);

  @override
  Future<bool> crateApiMatrixIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "is_logged_in", argNames: []);

  @override
  Future<List<AccountInfo>> crateApiMatrixListAccounts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_account_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixListAccountsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixListAccountsConstMeta =>
      const TaskConstMeta(debugName: "list_accounts", argNames: []);

  @override
  Future<AuthResult> crateApiMatrixLoginWithPassword({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLoginWithPasswordConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLoginWithPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "login_with_password",
        argNames: ["username", "password"],
      );

  @override
  Future<AuthResult> crateApiMatrixLoginWithToken({
    required String accessToken,
    required String userId,
    required String deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLoginWithTokenConstMeta,
        argValues: [accessToken, userId, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLoginWithTokenConstMeta =>
      const TaskConstMeta(
        debugName: "login_with_token",
        argNames: ["accessToken", "userId", "deviceId"],
      );

  @override
  Future<void> crateApiMatrixLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<String?> crateApiMatrixMxcToHttp({required String mxcUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mxcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixMxcToHttpConstMeta,
        argValues: [mxcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMxcToHttpConstMeta =>
      const TaskConstMeta(debugName: "mxc_to_http", argNames: ["mxcUrl"]);

  @override
  Future<String?> crateApiMatrixMxcToHttpFull({required String mxcUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mxcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixMxcToHttpFullConstMeta,
        argValues: [mxcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMxcToHttpFullConstMeta =>
      const TaskConstMeta(debugName: "mxc_to_http_full", argNames: ["mxcUrl"]);

  @override
  Future<void> crateApiMatrixRedactMessage({
    required String roomId,
    required String eventId,
    String? reason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          sse_encode_opt_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRedactMessageConstMeta,
        argValues: [roomId, eventId, reason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRedactMessageConstMeta =>
      const TaskConstMeta(
        debugName: "redact_message",
        argNames: ["roomId", "eventId", "reason"],
      );

  @override
  Future<AuthResult> crateApiMatrixRegisterCompleteUiaa({
    required String username,
    required String password,
    required String registrationToken,
    required String session,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(registrationToken, serializer);
          sse_encode_String(session, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRegisterCompleteUiaaConstMeta,
        argValues: [username, password, registrationToken, session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRegisterCompleteUiaaConstMeta =>
      const TaskConstMeta(
        debugName: "register_complete_uiaa",
        argNames: ["username", "password", "registrationToken", "session"],
      );

  @override
  Future<AuthResult> crateApiMatrixRegisterGetUiaaSession({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRegisterGetUiaaSessionConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRegisterGetUiaaSessionConstMeta =>
      const TaskConstMeta(
        debugName: "register_get_uiaa_session",
        argNames: ["username", "password"],
      );

  @override
  Future<void> crateApiMatrixRemoveAccount({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRemoveAccountConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRemoveAccountConstMeta =>
      const TaskConstMeta(debugName: "remove_account", argNames: ["userId"]);

  @override
  Future<void> crateApiMatrixRestoreSession({
    required StoredSession session,
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_stored_session(session, serializer);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRestoreSessionConstMeta,
        argValues: [session, dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRestoreSessionConstMeta =>
      const TaskConstMeta(
        debugName: "restore_session",
        argNames: ["session", "dataDir"],
      );

  @override
  Future<List<ChatRoom>> crateApiMatrixSearchRooms({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_room,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSearchRoomsConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSearchRoomsConstMeta =>
      const TaskConstMeta(debugName: "search_rooms", argNames: ["query"]);

  @override
  Future<void> crateApiMatrixSendImageMessage({
    required String roomId,
    required List<int> imageData,
    required String filename,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          sse_encode_String(filename, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendImageMessageConstMeta,
        argValues: [roomId, imageData, filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendImageMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_image_message",
        argNames: ["roomId", "imageData", "filename"],
      );

  @override
  Future<void> crateApiMatrixSendMessage({
    required String roomId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendMessageConstMeta,
        argValues: [roomId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["roomId", "message"],
  );

  @override
  Future<void> crateApiMatrixSendReply({
    required String roomId,
    required String message,
    required String replyToEventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(replyToEventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendReplyConstMeta,
        argValues: [roomId, message, replyToEventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendReplyConstMeta => const TaskConstMeta(
    debugName: "send_reply",
    argNames: ["roomId", "message", "replyToEventId"],
  );

  @override
  Future<void> crateApiMatrixSendTypingNotice({
    required String roomId,
    required bool typing,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_bool(typing, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendTypingNoticeConstMeta,
        argValues: [roomId, typing],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendTypingNoticeConstMeta =>
      const TaskConstMeta(
        debugName: "send_typing_notice",
        argNames: ["roomId", "typing"],
      );

  @override
  Future<void> crateApiMatrixStartSync() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixStartSyncConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixStartSyncConstMeta =>
      const TaskConstMeta(debugName: "start_sync", argNames: []);

  @override
  Future<bool> crateApiMatrixSwitchAccount({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixSwitchAccountConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSwitchAccountConstMeta =>
      const TaskConstMeta(debugName: "switch_account", argNames: ["userId"]);

  @override
  Future<void> crateApiMatrixSyncOnce() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSyncOnceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSyncOnceConstMeta =>
      const TaskConstMeta(debugName: "sync_once", argNames: []);

  @override
  Stream<AppLogEntry> crateApiMatrixWatchAppLogs() {
    final sink = RustStreamSink<AppLogEntry>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_app_log_entry_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 42,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMatrixWatchAppLogsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixWatchAppLogsConstMeta =>
      const TaskConstMeta(debugName: "watch_app_logs", argNames: ["sink"]);

  @override
  Stream<SyncEvent> crateApiMatrixWatchSyncEvents() {
    final sink = RustStreamSink<SyncEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sync_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 43,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMatrixWatchSyncEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixWatchSyncEventsConstMeta =>
      const TaskConstMeta(debugName: "watch_sync_events", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AppLogEntry> dco_decode_StreamSink_app_log_entry_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountInfo dco_decode_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AccountInfo(
      userId: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      homeserverUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  AppLogEntry dco_decode_app_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppLogEntry(
      timestamp: dco_decode_i_64(arr[0]),
      level: dco_decode_String(arr[1]),
      tag: dco_decode_String(arr[2]),
      message: dco_decode_String(arr[3]),
    );
  }

  @protected
  AuthResult dco_decode_auth_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AuthResult(
      success: dco_decode_bool(arr[0]),
      userId: dco_decode_opt_String(arr[1]),
      deviceId: dco_decode_opt_String(arr[2]),
      accessToken: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
      needsUiaa: dco_decode_bool(arr[5]),
      session: dco_decode_opt_String(arr[6]),
      flows: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  StoredSession dco_decode_box_autoadd_stored_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stored_session(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ChatMessage(
      id: dco_decode_String(arr[0]),
      senderId: dco_decode_String(arr[1]),
      senderName: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      timestamp: dco_decode_String(arr[4]),
      isMe: dco_decode_bool(arr[5]),
      msgType: dco_decode_message_type(arr[6]),
      imageUrl: dco_decode_opt_String(arr[7]),
      inReplyTo: dco_decode_opt_String(arr[8]),
      isEdited: dco_decode_bool(arr[9]),
      editHistory: dco_decode_list_String(arr[10]),
    );
  }

  @protected
  ChatRoom dco_decode_chat_room(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ChatRoom(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_opt_String(arr[2]),
      lastMessage: dco_decode_String(arr[3]),
      lastMessageTime: dco_decode_String(arr[4]),
      unreadCount: dco_decode_i_32(arr[5]),
      isPinned: dco_decode_bool(arr[6]),
      isMuted: dco_decode_bool(arr[7]),
      roomType: dco_decode_String(arr[8]),
    );
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatus.values[raw as int];
  }

  @protected
  Contact dco_decode_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Contact(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_opt_String(arr[2]),
      status: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_account_info).toList();
  }

  @protected
  List<AppLogEntry> dco_decode_list_app_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_log_entry).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  List<ChatRoom> dco_decode_list_chat_room(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_room).toList();
  }

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_contact).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Space> dco_decode_list_space(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_space).toList();
  }

  @protected
  MessageType dco_decode_message_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  StoredSession? dco_decode_opt_box_autoadd_stored_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_stored_session(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Space dco_decode_space(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Space(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  StoredSession dco_decode_stored_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StoredSession(
      homeserverUrl: dco_decode_String(arr[0]),
      accessToken: dco_decode_String(arr[1]),
      userId: dco_decode_String(arr[2]),
      deviceId: dco_decode_String(arr[3]),
    );
  }

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SyncEvent_SyncCompleted();
      case 1:
        return SyncEvent_MessageSent(roomId: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AppLogEntry> sse_decode_StreamSink_app_log_entry_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_homeserverUrl = sse_decode_String(deserializer);
    return AccountInfo(
      userId: var_userId,
      deviceId: var_deviceId,
      homeserverUrl: var_homeserverUrl,
    );
  }

  @protected
  AppLogEntry sse_decode_app_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_level = sse_decode_String(deserializer);
    var var_tag = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return AppLogEntry(
      timestamp: var_timestamp,
      level: var_level,
      tag: var_tag,
      message: var_message,
    );
  }

  @protected
  AuthResult sse_decode_auth_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_userId = sse_decode_opt_String(deserializer);
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_accessToken = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_needsUiaa = sse_decode_bool(deserializer);
    var var_session = sse_decode_opt_String(deserializer);
    var var_flows = sse_decode_opt_String(deserializer);
    return AuthResult(
      success: var_success,
      userId: var_userId,
      deviceId: var_deviceId,
      accessToken: var_accessToken,
      error: var_error,
      needsUiaa: var_needsUiaa,
      session: var_session,
      flows: var_flows,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  StoredSession sse_decode_box_autoadd_stored_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stored_session(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_isMe = sse_decode_bool(deserializer);
    var var_msgType = sse_decode_message_type(deserializer);
    var var_imageUrl = sse_decode_opt_String(deserializer);
    var var_inReplyTo = sse_decode_opt_String(deserializer);
    var var_isEdited = sse_decode_bool(deserializer);
    var var_editHistory = sse_decode_list_String(deserializer);
    return ChatMessage(
      id: var_id,
      senderId: var_senderId,
      senderName: var_senderName,
      content: var_content,
      timestamp: var_timestamp,
      isMe: var_isMe,
      msgType: var_msgType,
      imageUrl: var_imageUrl,
      inReplyTo: var_inReplyTo,
      isEdited: var_isEdited,
      editHistory: var_editHistory,
    );
  }

  @protected
  ChatRoom sse_decode_chat_room(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_lastMessage = sse_decode_String(deserializer);
    var var_lastMessageTime = sse_decode_String(deserializer);
    var var_unreadCount = sse_decode_i_32(deserializer);
    var var_isPinned = sse_decode_bool(deserializer);
    var var_isMuted = sse_decode_bool(deserializer);
    var var_roomType = sse_decode_String(deserializer);
    return ChatRoom(
      id: var_id,
      name: var_name,
      avatarUrl: var_avatarUrl,
      lastMessage: var_lastMessage,
      lastMessageTime: var_lastMessageTime,
      unreadCount: var_unreadCount,
      isPinned: var_isPinned,
      isMuted: var_isMuted,
      roomType: var_roomType,
    );
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionStatus.values[inner];
  }

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return Contact(
      id: var_id,
      name: var_name,
      avatarUrl: var_avatarUrl,
      status: var_status,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AccountInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_account_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppLogEntry> sse_decode_list_app_log_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppLogEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_log_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatRoom> sse_decode_list_chat_room(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatRoom>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_room(deserializer));
    }
    return ans_;
  }

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Contact>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_contact(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Space> sse_decode_list_space(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Space>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_space(deserializer));
    }
    return ans_;
  }

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoredSession? sse_decode_opt_box_autoadd_stored_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_stored_session(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Space sse_decode_space(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    return Space(id: var_id, name: var_name, avatarUrl: var_avatarUrl);
  }

  @protected
  StoredSession sse_decode_stored_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_homeserverUrl = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    return StoredSession(
      homeserverUrl: var_homeserverUrl,
      accessToken: var_accessToken,
      userId: var_userId,
      deviceId: var_deviceId,
    );
  }

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return SyncEvent_SyncCompleted();
      case 1:
        var var_roomId = sse_decode_String(deserializer);
        return SyncEvent_MessageSent(roomId: var_roomId);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_app_log_entry_Sse(
    RustStreamSink<AppLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.homeserverUrl, serializer);
  }

  @protected
  void sse_encode_app_log_entry(AppLogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.level, serializer);
    sse_encode_String(self.tag, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_auth_result(AuthResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.userId, serializer);
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_opt_String(self.accessToken, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_bool(self.needsUiaa, serializer);
    sse_encode_opt_String(self.session, serializer);
    sse_encode_opt_String(self.flows, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_stored_session(
    StoredSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stored_session(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_bool(self.isMe, serializer);
    sse_encode_message_type(self.msgType, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_opt_String(self.inReplyTo, serializer);
    sse_encode_bool(self.isEdited, serializer);
    sse_encode_list_String(self.editHistory, serializer);
  }

  @protected
  void sse_encode_chat_room(ChatRoom self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_String(self.lastMessage, serializer);
    sse_encode_String(self.lastMessageTime, serializer);
    sse_encode_i_32(self.unreadCount, serializer);
    sse_encode_bool(self.isPinned, serializer);
    sse_encode_bool(self.isMuted, serializer);
    sse_encode_String(self.roomType, serializer);
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_account_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_log_entry(
    List<AppLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_log_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_room(
    List<ChatRoom> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_room(item, serializer);
    }
  }

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_contact(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_space(List<Space> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_space(item, serializer);
    }
  }

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_stored_session(
    StoredSession? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_stored_session(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_space(Space self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
  }

  @protected
  void sse_encode_stored_session(StoredSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.homeserverUrl, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
  }

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SyncEvent_SyncCompleted():
        sse_encode_i_32(0, serializer);
      case SyncEvent_MessageSent(roomId: final roomId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(roomId, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
