// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_timestamp`, `get_client`, `get_last_message_info`, `store_client`, `try_extract_uiaa`, `try_parse_uiaa_from_string`, `uiaa_to_auth_result`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncNotification`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Create a Matrix client for the given homeserver URL.
/// Must be called before any registration / login attempt.
Future<void> createClient({required String homeserverUrl}) => RustLib
    .instance
    .api
    .crateApiMatrixCreateClient(homeserverUrl: homeserverUrl);

/// Step 1 of registration: send a register request without auth to discover
/// the UIAA session and flows. The server will respond with 401 + UIAA info.
Future<AuthResult> registerGetUiaaSession({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixRegisterGetUiaaSession(
  username: username,
  password: password,
);

/// Step 2 of registration: complete registration by providing the registration
/// token and the UIAA session obtained from register_get_uiaa_session.
Future<AuthResult> registerCompleteUiaa({
  required String username,
  required String password,
  required String registrationToken,
  required String session,
}) => RustLib.instance.api.crateApiMatrixRegisterCompleteUiaa(
  username: username,
  password: password,
  registrationToken: registrationToken,
  session: session,
);

/// Login with username and password.
Future<AuthResult> loginWithPassword({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixLoginWithPassword(
  username: username,
  password: password,
);

/// Login with an existing access token (restore session).
Future<AuthResult> loginWithToken({
  required String accessToken,
  required String userId,
  required String deviceId,
}) => RustLib.instance.api.crateApiMatrixLoginWithToken(
  accessToken: accessToken,
  userId: userId,
  deviceId: deviceId,
);

/// Check if the client is currently logged in.
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiMatrixIsLoggedIn();

/// Get the current user ID if logged in.
Future<String?> getCurrentUserId() =>
    RustLib.instance.api.crateApiMatrixGetCurrentUserId();

/// Logout the current user.
Future<void> logout() => RustLib.instance.api.crateApiMatrixLogout();

/// Get the current session if logged in, for persisting to disk.
Future<StoredSession?> getSession() =>
    RustLib.instance.api.crateApiMatrixGetSession();

/// Restore a previously saved session.
Future<void> restoreSession({required StoredSession session}) =>
    RustLib.instance.api.crateApiMatrixRestoreSession(session: session);

/// Perform an initial sync and then start a background sync loop.
/// Returns immediately after the initial sync. The background sync
/// runs forever via `client.sync()` which uses long-polling (30s timeout).
/// When new events arrive, we notify via the sync_state stream.
Future<void> syncOnce() => RustLib.instance.api.crateApiMatrixSyncOnce();

/// Start a background sync loop. This uses long-polling (the server holds
/// the connection for up to 30s waiting for new events, then responds).
/// After each response, it immediately starts the next poll.
/// This is the standard approach for Matrix clients — NOT polling.
Future<void> startSync() => RustLib.instance.api.crateApiMatrixStartSync();

/// Check if background sync is alive.
Future<bool> isConnected() => RustLib.instance.api.crateApiMatrixIsConnected();

ConnectionStatus getConnectionStatus() =>
    RustLib.instance.api.crateApiMatrixGetConnectionStatus();

Future<void> initClient() => RustLib.instance.api.crateApiMatrixInitClient();

/// Get all joined rooms (must sync first).
Future<List<ChatRoom>> getChatRooms() =>
    RustLib.instance.api.crateApiMatrixGetChatRooms();

/// Get messages for a room (must sync first).
Future<List<ChatMessage>> getMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetMessages(roomId: roomId);

/// Send a text message to a room.
Future<void> sendMessage({required String roomId, required String message}) =>
    RustLib.instance.api.crateApiMatrixSendMessage(
      roomId: roomId,
      message: message,
    );

/// Create a new direct chat room with a user.
/// Returns the new room ID.
Future<String> createDm({required String userId}) =>
    RustLib.instance.api.crateApiMatrixCreateDm(userId: userId);

/// Create a group room with a name and optional topic.
/// Returns the new room ID.
Future<String> createGroupRoom({required String name, String? topic}) => RustLib
    .instance
    .api
    .crateApiMatrixCreateGroupRoom(name: name, topic: topic);

Future<List<Space>> getSpaces() =>
    RustLib.instance.api.crateApiMatrixGetSpaces();

Future<List<Contact>> getContacts() =>
    RustLib.instance.api.crateApiMatrixGetContacts();

/// Result of a registration or login attempt
class AuthResult {
  final bool success;
  final String? userId;
  final String? deviceId;
  final String? accessToken;
  final String? error;

  /// If true, UIAA is needed — caller should call register_account again with token + session
  final bool needsUiaa;
  final String? session;

  /// Available UIAA flows (JSON)
  final String? flows;

  const AuthResult({
    required this.success,
    this.userId,
    this.deviceId,
    this.accessToken,
    this.error,
    required this.needsUiaa,
    this.session,
    this.flows,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode ^
      error.hashCode ^
      needsUiaa.hashCode ^
      session.hashCode ^
      flows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          error == other.error &&
          needsUiaa == other.needsUiaa &&
          session == other.session &&
          flows == other.flows;
}

class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String content;
  final String timestamp;
  final bool isMe;
  final MessageType msgType;
  final String? imageUrl;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.content,
    required this.timestamp,
    required this.isMe,
    required this.msgType,
    this.imageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      isMe.hashCode ^
      msgType.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          content == other.content &&
          timestamp == other.timestamp &&
          isMe == other.isMe &&
          msgType == other.msgType &&
          imageUrl == other.imageUrl;
}

class ChatRoom {
  final String id;
  final String name;
  final String? avatarUrl;
  final String lastMessage;
  final String lastMessageTime;
  final int unreadCount;
  final bool isPinned;
  final bool isMuted;

  const ChatRoom({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.lastMessage,
    required this.lastMessageTime,
    required this.unreadCount,
    required this.isPinned,
    required this.isMuted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      lastMessage.hashCode ^
      lastMessageTime.hashCode ^
      unreadCount.hashCode ^
      isPinned.hashCode ^
      isMuted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          lastMessage == other.lastMessage &&
          lastMessageTime == other.lastMessageTime &&
          unreadCount == other.unreadCount &&
          isPinned == other.isPinned &&
          isMuted == other.isMuted;
}

enum ConnectionStatus { connected, connecting, updating, disconnected }

class Contact {
  final String id;
  final String name;
  final String? avatarUrl;
  final String status;

  const Contact({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ avatarUrl.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          status == other.status;
}

enum MessageType { text, image }

class Space {
  final String id;
  final String name;
  final String? avatarUrl;

  const Space({required this.id, required this.name, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Space &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}

/// Session data to persist across app restarts.
class StoredSession {
  final String homeserverUrl;
  final String accessToken;
  final String userId;
  final String deviceId;

  const StoredSession({
    required this.homeserverUrl,
    required this.accessToken,
    required this.userId,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      accessToken.hashCode ^
      userId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredSession &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          accessToken == other.accessToken &&
          userId == other.userId &&
          deviceId == other.deviceId;
}
