// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'matrix.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `active_session_meta`, `app_log`, `build_sdk_data_dir`, `current_verification_session`, `extract_edit_text`, `finalize_pending`, `format_timestamp`, `get_client`, `get_last_message_info`, `install_verification_event_handler`, `notify_sync_event`, `sanitize_for_path`, `set_connection_status`, `stop_sync_task`, `strip_reply_fallback`, `try_extract_uiaa`, `try_parse_uiaa_from_string`, `try_start_sliding_sync`, `uiaa_to_auth_result`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientEntry`, `PendingEntry`, `SyncNotification`, `SyncTask`, `VerificationSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Stream app log entries from Rust → Dart (live).
Stream<AppLogEntry> watchAppLogs() =>
    RustLib.instance.api.crateApiMatrixWatchAppLogs();

/// Retrieve all buffered logs (up to 500 entries).
/// Call this once after connecting the stream to show historical logs.
List<AppLogEntry> getRecentLogs() =>
    RustLib.instance.api.crateApiMatrixGetRecentLogs();

/// Create a Matrix client for the given homeserver URL.
/// Must be called before any registration / login attempt.
/// The client is stored as "pending" until a login succeeds,
/// after which it is automatically migrated to a per-user store.
Future<void> createClient({
  required String homeserverUrl,
  required String dataDir,
}) => RustLib.instance.api.crateApiMatrixCreateClient(
  homeserverUrl: homeserverUrl,
  dataDir: dataDir,
);

/// Step 1 of registration: discover UIAA flows.
Future<AuthResult> registerGetUiaaSession({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixRegisterGetUiaaSession(
  username: username,
  password: password,
);

/// Step 2 of registration: complete with token + session.
Future<AuthResult> registerCompleteUiaa({
  required String username,
  required String password,
  required String registrationToken,
  required String session,
}) => RustLib.instance.api.crateApiMatrixRegisterCompleteUiaa(
  username: username,
  password: password,
  registrationToken: registrationToken,
  session: session,
);

/// Login with username and password.
Future<AuthResult> loginWithPassword({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixLoginWithPassword(
  username: username,
  password: password,
);

/// Login with an existing access token (restore session).
Future<AuthResult> loginWithToken({
  required String accessToken,
  required String userId,
  required String deviceId,
}) => RustLib.instance.api.crateApiMatrixLoginWithToken(
  accessToken: accessToken,
  userId: userId,
  deviceId: deviceId,
);

/// Check if the client is currently logged in.
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiMatrixIsLoggedIn();

/// Get the current user ID if logged in.
Future<String?> getCurrentUserId() =>
    RustLib.instance.api.crateApiMatrixGetCurrentUserId();

/// Get the currently active user ID (the account being used).
Future<String?> getActiveUserId() =>
    RustLib.instance.api.crateApiMatrixGetActiveUserId();

/// List all logged-in accounts.
Future<List<AccountInfo>> listAccounts() =>
    RustLib.instance.api.crateApiMatrixListAccounts();

/// Switch the active account. Returns true if the account exists and was activated.
Future<bool> switchAccount({required String userId}) =>
    RustLib.instance.api.crateApiMatrixSwitchAccount(userId: userId);

/// Logout the active user and remove its data.
Future<void> logout() => RustLib.instance.api.crateApiMatrixLogout();

/// Remove a specific account by user_id (logout + delete data).
Future<void> removeAccount({required String userId}) =>
    RustLib.instance.api.crateApiMatrixRemoveAccount(userId: userId);

/// Get the current session if logged in, for persisting to disk.
Future<StoredSession?> getSession() =>
    RustLib.instance.api.crateApiMatrixGetSession();

/// Restore a previously saved session (used on app startup).
/// Uses a per-user store directory so multiple accounts coexist.
Future<void> restoreSession({
  required StoredSession session,
  required String dataDir,
}) => RustLib.instance.api.crateApiMatrixRestoreSession(
  session: session,
  dataDir: dataDir,
);

Future<List<VerificationDevice>> listOwnDevices() =>
    RustLib.instance.api.crateApiMatrixListOwnDevices();

Future<void> startDeviceVerification({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiMatrixStartDeviceVerification(deviceId: deviceId);

Future<void> acceptDeviceVerification() =>
    RustLib.instance.api.crateApiMatrixAcceptDeviceVerification();

Future<DeviceVerificationStatus?> getDeviceVerificationStatus() =>
    RustLib.instance.api.crateApiMatrixGetDeviceVerificationStatus();

Future<void> confirmDeviceVerification() =>
    RustLib.instance.api.crateApiMatrixConfirmDeviceVerification();

Future<void> cancelDeviceVerification({required bool mismatch}) => RustLib
    .instance
    .api
    .crateApiMatrixCancelDeviceVerification(mismatch: mismatch);

Future<EncryptionRecoveryInfo> getEncryptionRecoveryInfo() =>
    RustLib.instance.api.crateApiMatrixGetEncryptionRecoveryInfo();

Future<void> recoverEncryption({required String recoveryKeyOrPassphrase}) =>
    RustLib.instance.api.crateApiMatrixRecoverEncryption(
      recoveryKeyOrPassphrase: recoveryKeyOrPassphrase,
    );

Future<String> enableEncryptionRecovery({String? passphrase}) => RustLib
    .instance
    .api
    .crateApiMatrixEnableEncryptionRecovery(passphrase: passphrase);

/// Perform an initial sync with a 30-second timeout.
/// Uses traditional /sync for the initial load (Sliding Sync needs
/// this data in the state store first).
Future<void> syncOnce() => RustLib.instance.api.crateApiMatrixSyncOnce();

/// Start a Sliding Sync loop for real-time updates.
/// Falls back to traditional sync_once loop if Sliding Sync is unavailable.
Future<void> startSync() => RustLib.instance.api.crateApiMatrixStartSync();

/// Stream real-time sync events from Rust → Dart.
/// Call this once on app start and listen for updates.
/// When a `SyncCompleted` event arrives, refresh the room list.
/// When a `MessageSent` event arrives, refresh that room's messages.
Stream<SyncEvent> watchSyncEvents() =>
    RustLib.instance.api.crateApiMatrixWatchSyncEvents();

/// Check if background sync is alive.
Future<bool> isConnected() => RustLib.instance.api.crateApiMatrixIsConnected();

ConnectionStatus getConnectionStatus() =>
    RustLib.instance.api.crateApiMatrixGetConnectionStatus();

Future<void> initClient() => RustLib.instance.api.crateApiMatrixInitClient();

/// Convert an mxc:// URI to a thumbnail HTTP URL for chat bubbles.
/// Format: `{homeserver}/_matrix/client/v1/media/thumbnail/{server}/{mediaId}?width=800&height=600&method=scale`
Future<String?> mxcToHttp({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixMxcToHttp(mxcUrl: mxcUrl);

/// Convert an mxc:// URI to a full-quality download HTTP URL.
/// Used for "原图" (original quality) preview.
Future<String?> mxcToHttpFull({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixMxcToHttpFull(mxcUrl: mxcUrl);

/// Download media content as raw bytes using the Matrix SDK's HTTP client.
/// This is more reliable than constructing URLs and loading from Flutter.
Future<Uint8List?> downloadMediaBytes({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixDownloadMediaBytes(mxcUrl: mxcUrl);

/// Get the current access token for authenticated media requests.
Future<String?> getAccessToken() =>
    RustLib.instance.api.crateApiMatrixGetAccessToken();

Future<List<ChatRoom>> getChatRooms() =>
    RustLib.instance.api.crateApiMatrixGetChatRooms();

/// Get messages for a room (must sync first).
Future<List<ChatMessage>> getMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetMessages(roomId: roomId);

/// Send a text message to a room.
Future<void> sendMessage({required String roomId, required String message}) =>
    RustLib.instance.api.crateApiMatrixSendMessage(
      roomId: roomId,
      message: message,
    );

/// Send an image message to a room.
/// `image_data` is the raw bytes of the image file.
/// `filename` is the original file name (e.g. "photo.jpg").
Future<void> sendImageMessage({
  required String roomId,
  required List<int> imageData,
  required String filename,
}) => RustLib.instance.api.crateApiMatrixSendImageMessage(
  roomId: roomId,
  imageData: imageData,
  filename: filename,
);

/// Create a new direct chat room with a user.
Future<String> createDm({required String userId}) =>
    RustLib.instance.api.crateApiMatrixCreateDm(userId: userId);

/// Create a group room with a name and optional topic.
Future<String> createGroupRoom({required String name, String? topic}) => RustLib
    .instance
    .api
    .crateApiMatrixCreateGroupRoom(name: name, topic: topic);

Future<List<Space>> getSpaces() =>
    RustLib.instance.api.crateApiMatrixGetSpaces();

Future<List<Contact>> getContacts() =>
    RustLib.instance.api.crateApiMatrixGetContacts();

/// Send a reply to a specific message in a room.
Future<void> sendReply({
  required String roomId,
  required String message,
  required String replyToEventId,
}) => RustLib.instance.api.crateApiMatrixSendReply(
  roomId: roomId,
  message: message,
  replyToEventId: replyToEventId,
);

/// Redact (delete) a message from a room.
Future<void> redactMessage({
  required String roomId,
  required String eventId,
  String? reason,
}) => RustLib.instance.api.crateApiMatrixRedactMessage(
  roomId: roomId,
  eventId: eventId,
  reason: reason,
);

/// Send a typing notice to a room.
Future<void> sendTypingNotice({required String roomId, required bool typing}) =>
    RustLib.instance.api.crateApiMatrixSendTypingNotice(
      roomId: roomId,
      typing: typing,
    );

/// Get members of a room.
Future<List<Contact>> getRoomMembers({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetRoomMembers(roomId: roomId);

/// Get the avatar URL for a room.
Future<String?> getRoomAvatarUrl({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetRoomAvatarUrl(roomId: roomId);

/// Search rooms by name.
Future<List<ChatRoom>> searchRooms({required String query}) =>
    RustLib.instance.api.crateApiMatrixSearchRooms(query: query);

/// Load more messages (paginated) from before a given event.
Future<List<ChatMessage>> getMessagesBefore({
  required String roomId,
  required String fromEventId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixGetMessagesBefore(
  roomId: roomId,
  fromEventId: fromEventId,
  limit: limit,
);

/// Info about a logged-in account (for listing / switching).
class AccountInfo {
  final String userId;
  final String deviceId;
  final String homeserverUrl;

  const AccountInfo({
    required this.userId,
    required this.deviceId,
    required this.homeserverUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ deviceId.hashCode ^ homeserverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserverUrl == other.homeserverUrl;
}

/// A single log entry visible to the user.
class AppLogEntry {
  /// Milliseconds since Unix epoch
  final PlatformInt64 timestamp;

  /// log / warn / error
  final String level;

  /// What subsystem: sync, auth, rooms, media, etc.
  final String tag;

  /// The actual message
  final String message;

  const AppLogEntry({
    required this.timestamp,
    required this.level,
    required this.tag,
    required this.message,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ level.hashCode ^ tag.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppLogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          level == other.level &&
          tag == other.tag &&
          message == other.message;
}

/// Result of a registration or login attempt
class AuthResult {
  final bool success;
  final String? userId;
  final String? deviceId;
  final String? accessToken;
  final String? error;

  /// If true, UIAA is needed — caller should call register_account again with token + session
  final bool needsUiaa;
  final String? session;

  /// Available UIAA flows (JSON)
  final String? flows;

  const AuthResult({
    required this.success,
    this.userId,
    this.deviceId,
    this.accessToken,
    this.error,
    required this.needsUiaa,
    this.session,
    this.flows,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode ^
      error.hashCode ^
      needsUiaa.hashCode ^
      session.hashCode ^
      flows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          error == other.error &&
          needsUiaa == other.needsUiaa &&
          session == other.session &&
          flows == other.flows;
}

class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String content;
  final String timestamp;
  final bool isMe;
  final MessageType msgType;
  final String? imageUrl;

  /// Event ID this message is replying to, if any.
  final String? inReplyTo;

  /// Whether this message has been edited.
  final bool isEdited;

  /// History of edits (previous versions), oldest first.
  final List<String> editHistory;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.content,
    required this.timestamp,
    required this.isMe,
    required this.msgType,
    this.imageUrl,
    this.inReplyTo,
    required this.isEdited,
    required this.editHistory,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      isMe.hashCode ^
      msgType.hashCode ^
      imageUrl.hashCode ^
      inReplyTo.hashCode ^
      isEdited.hashCode ^
      editHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          content == other.content &&
          timestamp == other.timestamp &&
          isMe == other.isMe &&
          msgType == other.msgType &&
          imageUrl == other.imageUrl &&
          inReplyTo == other.inReplyTo &&
          isEdited == other.isEdited &&
          editHistory == other.editHistory;
}

class ChatRoom {
  final String id;
  final String name;
  final String? avatarUrl;
  final String lastMessage;
  final String lastMessageTime;
  final int unreadCount;
  final bool isPinned;
  final bool isMuted;

  /// "dm", "group", or "space"
  final String roomType;

  const ChatRoom({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.lastMessage,
    required this.lastMessageTime,
    required this.unreadCount,
    required this.isPinned,
    required this.isMuted,
    required this.roomType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      lastMessage.hashCode ^
      lastMessageTime.hashCode ^
      unreadCount.hashCode ^
      isPinned.hashCode ^
      isMuted.hashCode ^
      roomType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          lastMessage == other.lastMessage &&
          lastMessageTime == other.lastMessageTime &&
          unreadCount == other.unreadCount &&
          isPinned == other.isPinned &&
          isMuted == other.isMuted &&
          roomType == other.roomType;
}

enum ConnectionStatus { connected, connecting, updating, disconnected }

class Contact {
  final String id;
  final String name;
  final String? avatarUrl;
  final String status;

  const Contact({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ avatarUrl.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          status == other.status;
}

class DeviceVerificationStatus {
  final String phase;
  final String deviceId;
  final String flowId;
  final bool incoming;
  final List<VerificationEmoji> emojis;
  final String message;

  const DeviceVerificationStatus({
    required this.phase,
    required this.deviceId,
    required this.flowId,
    required this.incoming,
    required this.emojis,
    required this.message,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      deviceId.hashCode ^
      flowId.hashCode ^
      incoming.hashCode ^
      emojis.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceVerificationStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          deviceId == other.deviceId &&
          flowId == other.flowId &&
          incoming == other.incoming &&
          emojis == other.emojis &&
          message == other.message;
}

class EncryptionRecoveryInfo {
  final String state;
  final bool deviceVerified;

  const EncryptionRecoveryInfo({
    required this.state,
    required this.deviceVerified,
  });

  @override
  int get hashCode => state.hashCode ^ deviceVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptionRecoveryInfo &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          deviceVerified == other.deviceVerified;
}

enum MessageType {
  text,
  image,

  /// State/member change event (join, leave, etc.)
  event,
}

class Space {
  final String id;
  final String name;
  final String? avatarUrl;

  const Space({required this.id, required this.name, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Space &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}

/// Session data to persist across app restarts.
class StoredSession {
  final String homeserverUrl;
  final String accessToken;
  final String userId;
  final String deviceId;

  const StoredSession({
    required this.homeserverUrl,
    required this.accessToken,
    required this.userId,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      accessToken.hashCode ^
      userId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredSession &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          accessToken == other.accessToken &&
          userId == other.userId &&
          deviceId == other.deviceId;
}

@freezed
sealed class SyncEvent with _$SyncEvent {
  const SyncEvent._();

  /// A sync cycle completed (rooms may have new messages).
  const factory SyncEvent.syncCompleted() = SyncEvent_SyncCompleted;

  /// A message was sent (room list should refresh).
  const factory SyncEvent.messageSent({required String roomId}) =
      SyncEvent_MessageSent;
}

class VerificationDevice {
  final String deviceId;
  final String displayName;
  final bool isCurrent;
  final bool isVerified;

  const VerificationDevice({
    required this.deviceId,
    required this.displayName,
    required this.isCurrent,
    required this.isVerified,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      displayName.hashCode ^
      isCurrent.hashCode ^
      isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isCurrent == other.isCurrent &&
          isVerified == other.isVerified;
}

class VerificationEmoji {
  final String symbol;
  final String description;

  const VerificationEmoji({required this.symbol, required this.description});

  @override
  int get hashCode => symbol.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationEmoji &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          description == other.description;
}
