// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'matrix.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `account_image_pack_to_sticker_pack`, `active_session_meta`, `add_desired`, `app_log`, `build_mentions`, `build_sdk_data_dir`, `build_text_content`, `clear_timeline_cache`, `clear_verification_session_if`, `clear_verification_session`, `current_verification_session`, `encryption_settings`, `extract_edit_content`, `file_message_content`, `finalize_pending`, `friendly_auth_error`, `get_client`, `get_last_message_info`, `get_room_by_id`, `image_info_dimensions`, `image_mime_type`, `install_live_update_event_handlers`, `install_room_key_event_handler`, `install_verification_event_handler`, `load_room_sticker_packs`, `location_message_content`, `media_caption_parts`, `mentions_parts`, `mxc_to_thumbnail_http`, `notify_sync_event`, `pack_image_to_sticker`, `parse_supplied_mime_type`, `poll_start_content`, `poll_start_for_forward`, `receipt_extension_for_subscribed_rooms`, `remove_desired`, `remove_dir_all_if_exists`, `room_display_name`, `room_image_pack_to_sticker_pack`, `room_message_preview`, `room_state_label`, `room_to_chat_room`, `sanitize_for_path`, `sanitized_formatted_body`, `sanitized_reply_formatted_body`, `set_connection_status`, `sticker_info_dimensions`, `stop_sync_task`, `strip_reply_fallback`, `text_message_parts`, `try_extract_uiaa`, `try_parse_uiaa_from_string`, `try_start_sliding_sync`, `uiaa_to_auth_result`, `uint_to_i32`, `unable_to_decrypt_message`, `unstable_poll_preview`, `usage_allows_sticker`, `validate_poll_answer_ids`, `validated_geo_uri`, `video_mime_type`, `wait_for_e2ee_initialization`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientEntry`, `EditedTextContent`, `PendingEntry`, `RoomSubscriptionState`, `SyncNotification`, `SyncTask`, `VerificationSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Stream app log entries from Rust → Dart (live).
Stream<AppLogEntry> watchAppLogs() =>
    RustLib.instance.api.crateApiMatrixWatchAppLogs();

/// Retrieve all buffered logs (up to 500 entries).
/// Call this once after connecting the stream to show historical logs.
List<AppLogEntry> getRecentLogs() =>
    RustLib.instance.api.crateApiMatrixGetRecentLogs();

/// Create a Matrix client for the given homeserver URL.
/// Must be called before any registration / login attempt.
/// The client is stored as "pending" until a login succeeds,
/// after which it is automatically migrated to a per-user store.
Future<void> createClient({
  required String homeserverUrl,
  required String dataDir,
}) => RustLib.instance.api.crateApiMatrixCreateClient(
  homeserverUrl: homeserverUrl,
  dataDir: dataDir,
);

/// Step 1 of registration: discover UIAA flows.
Future<AuthResult> registerGetUiaaSession({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixRegisterGetUiaaSession(
  username: username,
  password: password,
);

/// Step 2 of registration: complete with token + session.
Future<AuthResult> registerCompleteUiaa({
  required String username,
  required String password,
  required String registrationToken,
  required String session,
}) => RustLib.instance.api.crateApiMatrixRegisterCompleteUiaa(
  username: username,
  password: password,
  registrationToken: registrationToken,
  session: session,
);

/// Login with username and password.
Future<AuthResult> loginWithPassword({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixLoginWithPassword(
  username: username,
  password: password,
);

/// Login with an existing access token (restore session).
Future<AuthResult> loginWithToken({
  required String accessToken,
  required String userId,
  required String deviceId,
  String? refreshToken,
}) => RustLib.instance.api.crateApiMatrixLoginWithToken(
  accessToken: accessToken,
  userId: userId,
  deviceId: deviceId,
  refreshToken: refreshToken,
);

/// Check if the client is currently logged in.
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiMatrixIsLoggedIn();

/// Get the current user ID if logged in.
Future<String?> getCurrentUserId() =>
    RustLib.instance.api.crateApiMatrixGetCurrentUserId();

/// Get the currently active user ID (the account being used).
Future<String?> getActiveUserId() =>
    RustLib.instance.api.crateApiMatrixGetActiveUserId();

/// Fetch the current user's profile (display name + avatar mxc URL) from the
/// homeserver. Used to populate the profile editor with current values.
Future<UserProfile> getProfile() =>
    RustLib.instance.api.crateApiMatrixGetProfile();

/// Update the current user's display name. Empty string clears it.
Future<void> setDisplayName({required String name}) =>
    RustLib.instance.api.crateApiMatrixSetDisplayName(name: name);

/// Update the current user's avatar. `mxc` is an `mxc://` URI obtained from
/// `upload_avatar`. Pass an empty string to remove the avatar.
Future<void> setAvatarUrl({required String mxc}) =>
    RustLib.instance.api.crateApiMatrixSetAvatarUrl(mxc: mxc);

/// Upload raw image bytes as avatar media and return the resulting `mxc://`
/// URI. Call `set_avatar_url` afterwards to actually apply it. Split into two
/// steps so the UI can show progress if needed and a failed upload won't leave
/// a half-set profile.
Future<String> uploadAvatar({
  required String contentType,
  required List<int> data,
}) => RustLib.instance.api.crateApiMatrixUploadAvatar(
  contentType: contentType,
  data: data,
);

/// List all logged-in accounts.
Future<List<AccountInfo>> listAccounts() =>
    RustLib.instance.api.crateApiMatrixListAccounts();

/// Switch the active account. Returns true if the account exists and was activated.
Future<bool> switchAccount({required String userId}) =>
    RustLib.instance.api.crateApiMatrixSwitchAccount(userId: userId);

/// Logout the active user and remove its data.
Future<void> logout() => RustLib.instance.api.crateApiMatrixLogout();

/// Remove a specific account by user_id (logout + delete data).
Future<void> removeAccount({required String userId}) =>
    RustLib.instance.api.crateApiMatrixRemoveAccount(userId: userId);

/// Get the current session if logged in, for persisting to disk.
Future<StoredSession?> getSession() =>
    RustLib.instance.api.crateApiMatrixGetSession();

/// Restore a previously saved session (used on app startup).
/// Uses a per-user store directory so multiple accounts coexist.
Future<void> restoreSession({
  required StoredSession session,
  required String dataDir,
}) => RustLib.instance.api.crateApiMatrixRestoreSession(
  session: session,
  dataDir: dataDir,
);

Future<List<VerificationDevice>> listOwnDevices() =>
    RustLib.instance.api.crateApiMatrixListOwnDevices();

Future<void> startDeviceVerification({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiMatrixStartDeviceVerification(deviceId: deviceId);

Future<void> acceptDeviceVerification() =>
    RustLib.instance.api.crateApiMatrixAcceptDeviceVerification();

Future<DeviceVerificationStatus?> getDeviceVerificationStatus() =>
    RustLib.instance.api.crateApiMatrixGetDeviceVerificationStatus();

Future<void> confirmDeviceVerification() =>
    RustLib.instance.api.crateApiMatrixConfirmDeviceVerification();

Future<void> cancelDeviceVerification({required bool mismatch}) => RustLib
    .instance
    .api
    .crateApiMatrixCancelDeviceVerification(mismatch: mismatch);

Future<EncryptionRecoveryInfo> getEncryptionRecoveryInfo() =>
    RustLib.instance.api.crateApiMatrixGetEncryptionRecoveryInfo();

Future<void> recoverEncryption({required String recoveryKeyOrPassphrase}) =>
    RustLib.instance.api.crateApiMatrixRecoverEncryption(
      recoveryKeyOrPassphrase: recoveryKeyOrPassphrase,
    );

Future<String> enableEncryptionRecovery({String? passphrase}) => RustLib
    .instance
    .api
    .crateApiMatrixEnableEncryptionRecovery(passphrase: passphrase);

/// Perform an initial sync with a 30-second timeout.
/// Uses traditional /sync for the initial load (Sliding Sync needs
/// this data in the state store first).
Future<void> syncOnce() => RustLib.instance.api.crateApiMatrixSyncOnce();

/// Start a Sliding Sync loop for real-time updates.
/// Falls back to traditional sync_once loop if Sliding Sync is unavailable.
Future<void> startSync() => RustLib.instance.api.crateApiMatrixStartSync();

/// Stream real-time sync events from Rust → Dart.
/// Call this once on app start and listen for updates.
/// When a `SyncCompleted` event arrives, refresh the room list.
/// When a `MessageSent` event arrives, refresh that room's messages.
Stream<SyncEvent> watchSyncEvents() =>
    RustLib.instance.api.crateApiMatrixWatchSyncEvents();

/// Stream typing-notification updates (room_id + typing user ids) to Dart.
/// Mirrors `watch_sync_events`.
Stream<TypingNotification> watchTypingNotifications() =>
    RustLib.instance.api.crateApiMatrixWatchTypingNotifications();

/// Begin listening for typing notifications in `room_id`. Any previous
/// subscription for another room is cancelled first (only one room is
/// tracked at a time). Call `unsubscribe_typing` when leaving the room.
Future<void> subscribeTypingForRoom({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixSubscribeTypingForRoom(roomId: roomId);

/// Stop tracking typing notifications (e.g. when leaving the room screen).
Future<void> unsubscribeTyping() =>
    RustLib.instance.api.crateApiMatrixUnsubscribeTyping();

/// Subscribe to the given room in the Sliding Sync instance so that it is
/// included in every sync roundtrip, ensuring read-receipt deltas for it are
/// always delivered. Call when entering a room screen.
///
/// If Sliding Sync is not yet ready (startup race / account switch), the
/// desire is recorded and applied automatically once the sync loop publishes
/// an instance; this function never fails for that reason.
///
/// `desired`/`active` are updated under a single lock so concurrent calls
/// can't interleave (a late-finishing old subscribe can't overwrite a newer
/// room).
Future<void> subscribeRoomForReceipts({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixSubscribeRoomForReceipts(roomId: roomId);

/// Unsubscribe the given room from Sliding Sync (e.g. when leaving the room
/// screen). Receipts for it will still arrive when the room has timeline
/// activity, but not on every roundtrip. Uses `unsubscribe_to_rooms` (not a
/// no-op re-subscribe) so the subscription is actually removed, keeping sync
/// cost bounded as the user visits different rooms.
///
/// The room is removed only after its last mounted owner unsubscribes. The
/// update runs under the same lock as subscribe, so overlapping routes cannot
/// cancel each other's subscription.
Future<void> unsubscribeRoomForReceipts({required String roomId}) => RustLib
    .instance
    .api
    .crateApiMatrixUnsubscribeRoomForReceipts(roomId: roomId);

/// Check if background sync is alive.
Future<bool> isConnected() => RustLib.instance.api.crateApiMatrixIsConnected();

ConnectionStatus getConnectionStatus() =>
    RustLib.instance.api.crateApiMatrixGetConnectionStatus();

Future<void> initClient() => RustLib.instance.api.crateApiMatrixInitClient();

/// Convert an mxc:// URI to an avatar-sized thumbnail HTTP URL.
/// Format: `{homeserver}/_matrix/client/v1/media/thumbnail/{server}/{mediaId}?width=96&height=96&method=scale`
Future<String?> mxcToHttpAvatar({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixMxcToHttpAvatar(mxcUrl: mxcUrl);

/// Convert an mxc:// URI to a scaled thumbnail HTTP URL for message media.
Future<String?> mxcToHttpThumbnail({
  required String mxcUrl,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiMatrixMxcToHttpThumbnail(
  mxcUrl: mxcUrl,
  width: width,
  height: height,
);

/// Convert an mxc:// URI to a thumbnail HTTP URL for chat bubbles.
/// Format: `{homeserver}/_matrix/client/v1/media/thumbnail/{server}/{mediaId}?width=800&height=600&method=scale`
Future<String?> mxcToHttp({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixMxcToHttp(mxcUrl: mxcUrl);

/// Convert an mxc:// URI to a full-quality download HTTP URL.
/// Used for "原图" (original quality) preview.
Future<String?> mxcToHttpFull({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixMxcToHttpFull(mxcUrl: mxcUrl);

/// Download media content as raw bytes using the Matrix SDK's HTTP client.
/// This is more reliable than constructing URLs and loading from Flutter.
Future<Uint8List?> downloadMediaBytes({required String mxcUrl}) =>
    RustLib.instance.api.crateApiMatrixDownloadMediaBytes(mxcUrl: mxcUrl);

/// Download a Matrix media source, decrypting and integrity-checking encrypted
/// attachments through the SDK when necessary.
Future<Uint8List> downloadMediaSourceBytes({required String mediaSourceJson}) =>
    RustLib.instance.api.crateApiMatrixDownloadMediaSourceBytes(
      mediaSourceJson: mediaSourceJson,
    );

/// Get the current access token for authenticated media requests.
Future<String?> getAccessToken() =>
    RustLib.instance.api.crateApiMatrixGetAccessToken();

Future<String?> getRefreshToken() =>
    RustLib.instance.api.crateApiMatrixGetRefreshToken();

Future<bool> isRoomEncrypted({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixIsRoomEncrypted(roomId: roomId);

Future<List<ChatRoom>> getChatRooms() =>
    RustLib.instance.api.crateApiMatrixGetChatRooms();

/// Get messages for a room (must sync first).
Future<List<ChatMessage>> getMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetMessages(roomId: roomId);

Future<List<StickerPack>> getStickerPacks({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetStickerPacks(roomId: roomId);

Future<String> sendMessage({
  required String roomId,
  required FormattedMessageInput message,
}) => RustLib.instance.api.crateApiMatrixSendMessage(
  roomId: roomId,
  message: message,
);

/// Forward a message-like event into another room as a new event.
///
/// Text uses the already-aggregated content supplied by Flutter so edits are
/// forwarded at their latest visible revision. Media keeps its original
/// Matrix source, avoiding a lossy download and re-upload cycle; its caption
/// reflects the original event (the app does not currently aggregate media
/// caption edits — see `extract_edit_content`), so it matches what the user
/// sees in the bubble.
Future<String> forwardMessage({
  required String sourceRoomId,
  required String targetRoomId,
  required String eventId,
  required FormattedMessageInput text,
}) => RustLib.instance.api.crateApiMatrixForwardMessage(
  sourceRoomId: sourceRoomId,
  targetRoomId: targetRoomId,
  eventId: eventId,
  text: text,
);

/// Send an image message to a room.
/// `image_data` is the raw bytes of the image file.
/// `filename` is the original file name (e.g. "photo.jpg").
Future<void> sendImageMessage({
  required String roomId,
  required List<int> imageData,
  required String filename,
  String? mimeType,
  int? width,
  int? height,
}) => RustLib.instance.api.crateApiMatrixSendImageMessage(
  roomId: roomId,
  imageData: imageData,
  filename: filename,
  mimeType: mimeType,
  width: width,
  height: height,
);

/// Send an arbitrary file (document) attachment to a room.
Future<void> sendFileMessage({
  required String roomId,
  required List<int> fileData,
  required String filename,
  String? mimeType,
  int? size,
}) => RustLib.instance.api.crateApiMatrixSendFileMessage(
  roomId: roomId,
  fileData: fileData,
  filename: filename,
  mimeType: mimeType,
  size: size,
);

/// Send a video attachment to a room.
Future<void> sendVideoMessage({
  required String roomId,
  required List<int> videoData,
  required String filename,
  String? mimeType,
  int? width,
  int? height,
  int? durationMs,
  int? size,
}) => RustLib.instance.api.crateApiMatrixSendVideoMessage(
  roomId: roomId,
  videoData: videoData,
  filename: filename,
  mimeType: mimeType,
  width: width,
  height: height,
  durationMs: durationMs,
  size: size,
);

/// Share a geographic location as legacy `m.room.message` / `m.location`.
///
/// The extensible top-level `m.location` event is not parsed by the current
/// `matrix-sdk-ui` version. `geo_uri` follows RFC 5870, for example
/// `geo:37.786971,-122.399677`.
Future<void> sendLocation({
  required String roomId,
  required String body,
  required String geoUri,
}) => RustLib.instance.api.crateApiMatrixSendLocation(
  roomId: roomId,
  body: body,
  geoUri: geoUri,
);

/// Start a poll using the unstable `org.matrix.msc3381.poll.start` event.
///
/// This is the poll type surfaced by the current `matrix-sdk-ui` version; its
/// stable counterpart is not parsed there yet.
Future<void> sendPoll({
  required String roomId,
  required String question,
  required List<String> answers,
  required bool disclosed,
  required int maxSelections,
}) => RustLib.instance.api.crateApiMatrixSendPoll(
  roomId: roomId,
  question: question,
  answers: answers,
  disclosed: disclosed,
  maxSelections: maxSelections,
);

/// Submit a vote on a poll. Replaces the current user's previous response on
/// the same poll start event.
Future<void> sendPollResponse({
  required String roomId,
  required String pollStartEventId,
  required List<String> answerIds,
}) => RustLib.instance.api.crateApiMatrixSendPollResponse(
  roomId: roomId,
  pollStartEventId: pollStartEventId,
  answerIds: answerIds,
);

/// Close a poll so no further votes are accepted.
Future<void> endPoll({
  required String roomId,
  required String pollStartEventId,
}) => RustLib.instance.api.crateApiMatrixEndPoll(
  roomId: roomId,
  pollStartEventId: pollStartEventId,
);

Future<void> sendSticker({
  required String roomId,
  required String imageUrl,
  required String body,
  String? mimeType,
  int? width,
  int? height,
}) => RustLib.instance.api.crateApiMatrixSendSticker(
  roomId: roomId,
  imageUrl: imageUrl,
  body: body,
  mimeType: mimeType,
  width: width,
  height: height,
);

/// Create a new direct chat room with a user.
Future<String> createDm({required String userId}) =>
    RustLib.instance.api.crateApiMatrixCreateDm(userId: userId);

/// Create a group room with a name and optional topic.
Future<String> createGroupRoom({required String name, String? topic}) => RustLib
    .instance
    .api
    .crateApiMatrixCreateGroupRoom(name: name, topic: topic);

/// Create a space room with a name and optional topic.
Future<String> createSpace({required String name, String? topic}) =>
    RustLib.instance.api.crateApiMatrixCreateSpace(name: name, topic: topic);

/// Join a room or space by room ID or alias.
Future<String> joinRoom({required String identifier}) =>
    RustLib.instance.api.crateApiMatrixJoinRoom(identifier: identifier);

Future<void> acceptRoomInvite({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixAcceptRoomInvite(roomId: roomId);

Future<void> rejectRoomInvite({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRejectRoomInvite(roomId: roomId);

Future<void> withdrawRoomKnock({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixWithdrawRoomKnock(roomId: roomId);

Future<List<Space>> getSpaces() =>
    RustLib.instance.api.crateApiMatrixGetSpaces();

Future<SpaceDetails> getSpaceDetails({required String spaceId}) =>
    RustLib.instance.api.crateApiMatrixGetSpaceDetails(spaceId: spaceId);

Future<List<ChatRoom>> getSpaceChildren({required String spaceId}) =>
    RustLib.instance.api.crateApiMatrixGetSpaceChildren(spaceId: spaceId);

Future<void> updateSpaceDetails({
  required String spaceId,
  required String name,
  String? topic,
}) => RustLib.instance.api.crateApiMatrixUpdateSpaceDetails(
  spaceId: spaceId,
  name: name,
  topic: topic,
);

/// Add a room to a space, and advertise the reciprocal parent relation.
Future<void> addRoomToSpace({
  required String spaceId,
  required String roomId,
}) => RustLib.instance.api.crateApiMatrixAddRoomToSpace(
  spaceId: spaceId,
  roomId: roomId,
);

Future<void> removeRoomFromSpace({
  required String spaceId,
  required String roomId,
}) => RustLib.instance.api.crateApiMatrixRemoveRoomFromSpace(
  spaceId: spaceId,
  roomId: roomId,
);

Future<void> leaveSpace({required String spaceId}) =>
    RustLib.instance.api.crateApiMatrixLeaveSpace(spaceId: spaceId);

Future<List<ChatRoom>> getUngroupedRooms() =>
    RustLib.instance.api.crateApiMatrixGetUngroupedRooms();

Future<List<Contact>> getContacts() =>
    RustLib.instance.api.crateApiMatrixGetContacts();

/// Send a reply to a specific message in a room.
Future<String> sendReply({
  required String roomId,
  required FormattedMessageInput message,
  required String replyToEventId,
  String? replyToUserId,
}) => RustLib.instance.api.crateApiMatrixSendReply(
  roomId: roomId,
  message: message,
  replyToEventId: replyToEventId,
  replyToUserId: replyToUserId,
);

/// Edit (replace) one of your own messages.
///
/// Sends an `m.room.message` event whose `m.new_content` carries the new text
/// and whose `m.relates_to` is an `m.replace` pointing at the original event.
/// Tuwunel relays edits (MSC2676); the displayed edit history is aggregated
/// client-side by `get_messages` (see `Relation::Replacement` parsing).
Future<String> editMessage({
  required String roomId,
  required String eventId,
  required FormattedMessageInput message,
  required List<String> previousMentionedUserIds,
  required bool previousMentionsRoom,
}) => RustLib.instance.api.crateApiMatrixEditMessage(
  roomId: roomId,
  eventId: eventId,
  message: message,
  previousMentionedUserIds: previousMentionedUserIds,
  previousMentionsRoom: previousMentionsRoom,
);

/// Send an emoji reaction (m.annotation) to an event.
///
/// Re-sending the same key is de-duplicated server-side per MSC2677. To remove
/// a reaction, redact the reaction event (not implemented in this client yet).
Future<String> sendReaction({
  required String roomId,
  required String eventId,
  required String key,
}) => RustLib.instance.api.crateApiMatrixSendReaction(
  roomId: roomId,
  eventId: eventId,
  key: key,
);

/// Redact (delete) a message from a room.
Future<void> redactMessage({
  required String roomId,
  required String eventId,
  String? reason,
}) => RustLib.instance.api.crateApiMatrixRedactMessage(
  roomId: roomId,
  eventId: eventId,
  reason: reason,
);

/// Send a typing notice to a room.
Future<void> sendTypingNotice({required String roomId, required bool typing}) =>
    RustLib.instance.api.crateApiMatrixSendTypingNotice(
      roomId: roomId,
      typing: typing,
    );

/// Get members of a room.
Future<List<Contact>> getRoomMembers({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetRoomMembers(roomId: roomId);

/// Get the avatar URL for a room.
Future<String?> getRoomAvatarUrl({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetRoomAvatarUrl(roomId: roomId);

/// Search rooms by name.
Future<List<ChatRoom>> searchRooms({required String query}) =>
    RustLib.instance.api.crateApiMatrixSearchRooms(query: query);

/// Load more messages (paginated) from before a given event.
Future<List<ChatMessage>> getMessagesBefore({
  required String roomId,
  required String fromEventId,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixGetMessagesBefore(
  roomId: roomId,
  fromEventId: fromEventId,
  limit: limit,
);

/// Info about a logged-in account (for listing / switching).
class AccountInfo {
  final String userId;
  final String deviceId;
  final String homeserverUrl;

  const AccountInfo({
    required this.userId,
    required this.deviceId,
    required this.homeserverUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ deviceId.hashCode ^ homeserverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          homeserverUrl == other.homeserverUrl;
}

/// A single log entry visible to the user.
class AppLogEntry {
  /// Milliseconds since Unix epoch
  final PlatformInt64 timestamp;

  /// log / warn / error
  final String level;

  /// What subsystem: sync, auth, rooms, media, etc.
  final String tag;

  /// The actual message
  final String message;

  const AppLogEntry({
    required this.timestamp,
    required this.level,
    required this.tag,
    required this.message,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ level.hashCode ^ tag.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppLogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          level == other.level &&
          tag == other.tag &&
          message == other.message;
}

/// Result of a registration or login attempt
class AuthResult {
  final bool success;
  final String? userId;
  final String? deviceId;
  final String? accessToken;
  final String? refreshToken;
  final String? error;

  /// If true, UIAA is needed — caller should call register_account again with token + session
  final bool needsUiaa;
  final String? session;

  /// Available UIAA flows (JSON)
  final String? flows;

  const AuthResult({
    required this.success,
    this.userId,
    this.deviceId,
    this.accessToken,
    this.refreshToken,
    this.error,
    required this.needsUiaa,
    this.session,
    this.flows,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      error.hashCode ^
      needsUiaa.hashCode ^
      session.hashCode ^
      flows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          error == other.error &&
          needsUiaa == other.needsUiaa &&
          session == other.session &&
          flows == other.flows;
}

class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String content;

  /// Sanitized Matrix HTML for text-like messages.
  final String? formattedBody;
  final String? caption;

  /// Sanitized Matrix HTML for media captions.
  final String? captionFormattedBody;

  /// Intentional mentions carried by `m.mentions`.
  final List<String> mentionedUserIds;
  final bool mentionsRoom;
  final String timestamp;
  final bool isMe;
  final MessageType msgType;
  final String? imageUrl;

  /// Serialized Matrix MediaSource. Required to download encrypted media.
  final String? mediaSourceJson;
  final int? imageWidth;
  final int? imageHeight;

  /// Original filename for file/audio attachments.
  final String? filename;

  /// Declared file size in bytes for file/audio attachments.
  final int? fileSize;

  /// RFC 5870 geo URI for location messages (e.g. `geo:lat,lng`).
  final String? geoUri;

  /// Poll data when `msg_type == Poll`.
  final PollInfo? poll;

  /// Event ID this message is replying to, if any.
  final String? inReplyTo;

  /// Whether this message has been edited.
  final bool isEdited;

  /// History of edits (previous versions), oldest first.
  final List<String> editHistory;

  /// Emoji reactions on this message, one entry per distinct key.
  final List<Reaction> reactions;

  /// Members who have read up to this message (only populated for the
  /// current user's own messages; empty otherwise).
  final List<MessageReader> readers;

  /// Total joined member count of the room (including the current user).
  final int totalMembers;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.content,
    this.formattedBody,
    this.caption,
    this.captionFormattedBody,
    required this.mentionedUserIds,
    required this.mentionsRoom,
    required this.timestamp,
    required this.isMe,
    required this.msgType,
    this.imageUrl,
    this.mediaSourceJson,
    this.imageWidth,
    this.imageHeight,
    this.filename,
    this.fileSize,
    this.geoUri,
    this.poll,
    this.inReplyTo,
    required this.isEdited,
    required this.editHistory,
    required this.reactions,
    required this.readers,
    required this.totalMembers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      content.hashCode ^
      formattedBody.hashCode ^
      caption.hashCode ^
      captionFormattedBody.hashCode ^
      mentionedUserIds.hashCode ^
      mentionsRoom.hashCode ^
      timestamp.hashCode ^
      isMe.hashCode ^
      msgType.hashCode ^
      imageUrl.hashCode ^
      mediaSourceJson.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      filename.hashCode ^
      fileSize.hashCode ^
      geoUri.hashCode ^
      poll.hashCode ^
      inReplyTo.hashCode ^
      isEdited.hashCode ^
      editHistory.hashCode ^
      reactions.hashCode ^
      readers.hashCode ^
      totalMembers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          content == other.content &&
          formattedBody == other.formattedBody &&
          caption == other.caption &&
          captionFormattedBody == other.captionFormattedBody &&
          mentionedUserIds == other.mentionedUserIds &&
          mentionsRoom == other.mentionsRoom &&
          timestamp == other.timestamp &&
          isMe == other.isMe &&
          msgType == other.msgType &&
          imageUrl == other.imageUrl &&
          mediaSourceJson == other.mediaSourceJson &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          filename == other.filename &&
          fileSize == other.fileSize &&
          geoUri == other.geoUri &&
          poll == other.poll &&
          inReplyTo == other.inReplyTo &&
          isEdited == other.isEdited &&
          editHistory == other.editHistory &&
          reactions == other.reactions &&
          readers == other.readers &&
          totalMembers == other.totalMembers;
}

class ChatRoom {
  final String id;
  final String name;
  final String? avatarUrl;
  final String lastMessage;
  final String? lastMessageSender;
  final String lastMessageTime;
  final int unreadCount;

  /// "dm", "group", or "space"
  final String roomType;
  final bool isEncrypted;

  /// "joined", "invited", "knocked", "left", or "banned"
  final String roomState;

  const ChatRoom({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.lastMessage,
    this.lastMessageSender,
    required this.lastMessageTime,
    required this.unreadCount,
    required this.roomType,
    required this.isEncrypted,
    required this.roomState,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      lastMessage.hashCode ^
      lastMessageSender.hashCode ^
      lastMessageTime.hashCode ^
      unreadCount.hashCode ^
      roomType.hashCode ^
      isEncrypted.hashCode ^
      roomState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          lastMessage == other.lastMessage &&
          lastMessageSender == other.lastMessageSender &&
          lastMessageTime == other.lastMessageTime &&
          unreadCount == other.unreadCount &&
          roomType == other.roomType &&
          isEncrypted == other.isEncrypted &&
          roomState == other.roomState;
}

enum ConnectionStatus { connected, connecting, updating, disconnected }

class Contact {
  final String id;
  final String name;
  final String? avatarUrl;
  final String status;

  const Contact({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ avatarUrl.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          status == other.status;
}

class DeviceVerificationStatus {
  final String phase;
  final String deviceId;
  final String flowId;
  final bool incoming;
  final List<VerificationEmoji> emojis;
  final String message;

  const DeviceVerificationStatus({
    required this.phase,
    required this.deviceId,
    required this.flowId,
    required this.incoming,
    required this.emojis,
    required this.message,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      deviceId.hashCode ^
      flowId.hashCode ^
      incoming.hashCode ^
      emojis.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceVerificationStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          deviceId == other.deviceId &&
          flowId == other.flowId &&
          incoming == other.incoming &&
          emojis == other.emojis &&
          message == other.message;
}

class EncryptionRecoveryInfo {
  final String state;
  final bool deviceVerified;

  const EncryptionRecoveryInfo({
    required this.state,
    required this.deviceVerified,
  });

  @override
  int get hashCode => state.hashCode ^ deviceVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptionRecoveryInfo &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          deviceVerified == other.deviceVerified;
}

/// A Matrix text message compiled by the Flutter authoring layer.
///
/// `body` is always the readable plain-text fallback. `formatted_body`, when
/// present, is Matrix HTML and is sanitized again in Rust before sending.
class FormattedMessageInput {
  final String body;
  final String? formattedBody;
  final List<String> mentionedUserIds;
  final bool mentionsRoom;

  const FormattedMessageInput({
    required this.body,
    this.formattedBody,
    required this.mentionedUserIds,
    required this.mentionsRoom,
  });

  @override
  int get hashCode =>
      body.hashCode ^
      formattedBody.hashCode ^
      mentionedUserIds.hashCode ^
      mentionsRoom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormattedMessageInput &&
          runtimeType == other.runtimeType &&
          body == other.body &&
          formattedBody == other.formattedBody &&
          mentionedUserIds == other.mentionedUserIds &&
          mentionsRoom == other.mentionsRoom;
}

/// A single member's read receipt on a message.
class MessageReader {
  final String userId;

  /// Display name, falling back to the user id localpart.
  final String displayName;

  /// mxc:// avatar URL, if any.
  final String? avatarUrl;

  const MessageReader({
    required this.userId,
    required this.displayName,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ displayName.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageReader &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl;
}

enum MessageType {
  text,
  image,
  sticker,
  video,

  /// A generic document / file attachment (m.file, or m.audio rendered as
  /// a downloadable file).
  file,

  /// An m.poll.start (unstable org.matrix.msc3381) poll.
  poll,

  /// A legacy m.location message.
  location,

  /// State/member change event (join, leave, etc.)
  event,
}

/// One selectable answer of a poll.
class PollAnswerInfo {
  final String id;
  final String text;

  const PollAnswerInfo({required this.id, required this.text});

  @override
  int get hashCode => id.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PollAnswerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text;
}

/// Per-answer tally for a poll.
class PollAnswerResult {
  final String answerId;

  /// Number of users who selected this answer.
  final int count;

  /// Whether the current user selected this answer.
  final bool isMine;

  const PollAnswerResult({
    required this.answerId,
    required this.count,
    required this.isMine,
  });

  @override
  int get hashCode => answerId.hashCode ^ count.hashCode ^ isMine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PollAnswerResult &&
          runtimeType == other.runtimeType &&
          answerId == other.answerId &&
          count == other.count &&
          isMine == other.isMine;
}

/// Poll data carried by a `MessageType::Poll` message.
class PollInfo {
  final String question;
  final List<PollAnswerInfo> answers;

  /// Whether results are revealed while voting is open.
  final bool disclosed;

  /// Max selections allowed per voter.
  final int maxSelections;

  /// Answer ids the current user has already selected.
  final List<String> myAnswerIds;

  /// Per-answer tallies (only meaningful when disclosed or ended).
  final List<PollAnswerResult> results;

  /// Total distinct users who have voted.
  final int totalVoters;

  /// Whether the poll has been closed.
  final bool ended;

  const PollInfo({
    required this.question,
    required this.answers,
    required this.disclosed,
    required this.maxSelections,
    required this.myAnswerIds,
    required this.results,
    required this.totalVoters,
    required this.ended,
  });

  @override
  int get hashCode =>
      question.hashCode ^
      answers.hashCode ^
      disclosed.hashCode ^
      maxSelections.hashCode ^
      myAnswerIds.hashCode ^
      results.hashCode ^
      totalVoters.hashCode ^
      ended.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PollInfo &&
          runtimeType == other.runtimeType &&
          question == other.question &&
          answers == other.answers &&
          disclosed == other.disclosed &&
          maxSelections == other.maxSelections &&
          myAnswerIds == other.myAnswerIds &&
          results == other.results &&
          totalVoters == other.totalVoters &&
          ended == other.ended;
}

/// A single emoji reaction aggregated on a message.
class Reaction {
  /// The reaction key, e.g. "👍".
  final String key;

  /// User IDs that sent this reaction (excluding duplicates).
  final List<String> senders;

  /// Event id of the reaction event the current user sent for this key, if
  /// any. Used to toggle (redact) the user's own reaction.
  final String? myEventId;

  const Reaction({required this.key, required this.senders, this.myEventId});

  @override
  int get hashCode => key.hashCode ^ senders.hashCode ^ myEventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reaction &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          senders == other.senders &&
          myEventId == other.myEventId;
}

class Space {
  final String id;
  final String name;
  final String? avatarUrl;

  const Space({required this.id, required this.name, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Space &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}

class SpaceDetails {
  final String id;
  final String name;
  final String? avatarUrl;
  final String? topic;

  const SpaceDetails({
    required this.id,
    required this.name,
    this.avatarUrl,
    this.topic,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ avatarUrl.hashCode ^ topic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpaceDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          topic == other.topic;
}

class Sticker {
  final String id;
  final String shortcode;
  final String body;
  final String imageUrl;
  final String? thumbnailUrl;
  final String? mimeType;
  final int? width;
  final int? height;

  const Sticker({
    required this.id,
    required this.shortcode,
    required this.body,
    required this.imageUrl,
    this.thumbnailUrl,
    this.mimeType,
    this.width,
    this.height,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      shortcode.hashCode ^
      body.hashCode ^
      imageUrl.hashCode ^
      thumbnailUrl.hashCode ^
      mimeType.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sticker &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          shortcode == other.shortcode &&
          body == other.body &&
          imageUrl == other.imageUrl &&
          thumbnailUrl == other.thumbnailUrl &&
          mimeType == other.mimeType &&
          width == other.width &&
          height == other.height;
}

class StickerPack {
  final String id;
  final String title;
  final String? avatarUrl;

  /// "room" or "user"
  final String source;
  final List<Sticker> stickers;

  const StickerPack({
    required this.id,
    required this.title,
    this.avatarUrl,
    required this.source,
    required this.stickers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      avatarUrl.hashCode ^
      source.hashCode ^
      stickers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StickerPack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          avatarUrl == other.avatarUrl &&
          source == other.source &&
          stickers == other.stickers;
}

/// Session data to persist across app restarts.
class StoredSession {
  final String homeserverUrl;
  final String accessToken;
  final String? refreshToken;
  final String userId;
  final String deviceId;

  const StoredSession({
    required this.homeserverUrl,
    required this.accessToken,
    this.refreshToken,
    required this.userId,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      userId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredSession &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          userId == other.userId &&
          deviceId == other.deviceId;
}

@freezed
sealed class SyncEvent with _$SyncEvent {
  const SyncEvent._();

  /// A sync cycle completed (rooms may have new messages).
  const factory SyncEvent.syncCompleted() = SyncEvent_SyncCompleted;

  /// A message was sent (room list should refresh).
  const factory SyncEvent.messageSent({required String roomId}) =
      SyncEvent_MessageSent;
}

/// Ephemeral "who is typing right now" update for a room, pushed to Dart.
class TypingNotification {
  final String roomId;
  final List<String> userIds;

  const TypingNotification({required this.roomId, required this.userIds});

  @override
  int get hashCode => roomId.hashCode ^ userIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypingNotification &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          userIds == other.userIds;
}

/// The current user's profile, fetched from the homeserver for the editor.
class UserProfile {
  final String userId;
  final String displayName;

  /// `mxc://` avatar URI, if set.
  final String? avatarUrl;

  const UserProfile({
    required this.userId,
    required this.displayName,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ displayName.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl;
}

class VerificationDevice {
  final String deviceId;
  final String displayName;
  final bool isCurrent;
  final bool isVerified;

  const VerificationDevice({
    required this.deviceId,
    required this.displayName,
    required this.isCurrent,
    required this.isVerified,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      displayName.hashCode ^
      isCurrent.hashCode ^
      isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isCurrent == other.isCurrent &&
          isVerified == other.isVerified;
}

class VerificationEmoji {
  final String symbol;
  final String description;

  const VerificationEmoji({required this.symbol, required this.description});

  @override
  int get hashCode => symbol.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationEmoji &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          description == other.description;
}
