// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_client`, `controls_enabled`, `keywords_from_rules`, `notification_actions`, `settings_from_rules`, `target`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Read the server, including changes from other devices and writes not yet
/// echoed by sync. Never present SDK fallback defaults as saved preferences.
Future<NotificationPreferences> getNotificationRules({
  required String accountUserId,
}) => RustLib.instance.api.crateApiMatrixNotificationsGetNotificationRules(
  accountUserId: accountUserId,
);

/// Update one preference, preserving every other account/room/sender rule.
Future<void> setNotificationRule({
  required String accountUserId,
  required NotificationRule rule,
  required bool enabled,
}) => RustLib.instance.api.crateApiMatrixNotificationsSetNotificationRule(
  accountUserId: accountUserId,
  rule: rule,
  enabled: enabled,
);

/// Keyword rules apply to plaintext messages and are shared with other clients.
Future<void> setNotificationKeyword({
  required String accountUserId,
  required String keyword,
  required bool enabled,
}) => RustLib.instance.api.crateApiMatrixNotificationsSetNotificationKeyword(
  accountUserId: accountUserId,
  keyword: keyword,
  enabled: enabled,
);

class NotificationPreferences {
  final List<NotificationRuleSetting> rules;
  final List<String> keywords;

  const NotificationPreferences({required this.rules, required this.keywords});

  @override
  int get hashCode => rules.hashCode ^ keywords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationPreferences &&
          runtimeType == other.runtimeType &&
          rules == other.rules &&
          keywords == other.keywords;
}

/// Only expose account defaults; room and sender overrides remain untouched.
enum NotificationRule {
  muteAll,
  suppressNotices,
  userMention,
  roomMention,
  displayName,
  userName,
  roomNotif,
  invite,
  memberEvent,
  reaction,
  tombstone,
  call,
  directMessage,
  encryptedDirectMessage,
  groupMessage,
  encryptedGroupMessage,
  suppressEdits,
  pollStartDirect,
  pollStartGroup,
  pollEndDirect,
  pollEndGroup,
  pollResponse,
  subscribedThread,
  suppressUnsubscribedThreads,
}

class NotificationRuleSetting {
  final NotificationRule rule;
  final bool enabled;

  /// Older homeservers may omit mention or legacy rules.
  final bool supported;

  const NotificationRuleSetting({
    required this.rule,
    required this.enabled,
    required this.supported,
  });

  @override
  int get hashCode => rule.hashCode ^ enabled.hashCode ^ supported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationRuleSetting &&
          runtimeType == other.runtimeType &&
          rule == other.rule &&
          enabled == other.enabled &&
          supported == other.supported;
}
