// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_client`, `http_pusher`

/// Register on the named account, including inactive accounts on this device.
/// append=true preserves other users sharing this installation's subscription.
Future<void> registerHttpPusher({
  required String accountUserId,
  required String pushkey,
  required String appId,
  required String gatewayUrl,
  required String registrationId,
  String? webSubscription,
}) => RustLib.instance.api.crateApiMatrixPushRegisterHttpPusher(
  accountUserId: accountUserId,
  pushkey: pushkey,
  appId: appId,
  gatewayUrl: gatewayUrl,
  registrationId: registrationId,
  webSubscription: webSubscription,
);

Future<void> unregisterHttpPusher({
  required String accountUserId,
  required String pushkey,
  required String appId,
}) => RustLib.instance.api.crateApiMatrixPushUnregisterHttpPusher(
  accountUserId: accountUserId,
  pushkey: pushkey,
  appId: appId,
);
