name: Rust Tests

on:
  pull_request:
  push:
    branches:
      - main
      - test-fix

permissions:
  contents: read

env:
  FLUTTER_VERSION: 3.47.1

jobs:
  # Ideally we should split Flutter and Rust tests, but the Rust test requires
  # some generated files from the bridge so it depends on Flutter. Therefore,
  # we do both in the same workflow job run.
  flutter-and-rust-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, expand

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate Flutter Rust Bridge bindings
        run: |
          cargo install flutter_rust_bridge_codegen --version 2.13.0
          flutter_rust_bridge_codegen generate

      - name: Test application Rust crate
        run: cargo test --manifest-path rust/Cargo.toml --locked

      - name: Test vendored search crate
        run: cargo test --manifest-path rust/vendor/matrix-sdk-search/Cargo.toml

      - name: Clippy application Rust crate
        run: cargo clippy --manifest-path rust/Cargo.toml --locked

      - name: Clippy vendored search crate
        run: cargo clippy --manifest-path rust/vendor/matrix-sdk-search/Cargo.toml --locked

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run Dart tests
        run: flutter test
